### ISSUE TITLE
GUI display incompletely. 

### ISSUE THREAD

**Issue by jeffchen006** [CenturyLiu/Carla-GUI#3]
Hello, I wonder if you have met the similar problem before. 

Here the GUI displays incompletely. I cannot see "previous/next section" and arrows. 

![Screenshot from 2020-09-21 20-18-43](https://user-images.githubusercontent.com/37031265/93833944-3083a480-fc48-11ea-9e90-59d9872c995b.png)

**Comment by jeffchen006** [comment]
I'm welcoming any suggestions, comments, or thoughts. Thanks in advance.

**Comment by CenturyLiu** [comment]
The value you entered for the entry "Number of Freeway Sections" is 1. Therefore, no previous and next section will be shown. Try to change the number of intersection, and let us know if you still have problem with this issue.

**Comment by jeffchen006** [comment]
I find the reason why my GUI displays incompletely. Some codes of front-end require some pictures put under `images/` folder while others don not require that. 
However, for some reason, `/gui_interface/images/` folder is missing in this repo. I've put every pictures in `images/` folder now it should be fine.

**Comment by jeffchen006** [comment]
The latest commit should fix that problem.
